<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cosechas', 'doctrine');

/**
 * BaseCosechas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cosecha_id
 * @property string $descos
 * 
 * @method integer  getCosechaId()  Returns the current record's "cosecha_id" value
 * @method string   getDescos()     Returns the current record's "descos" value
 * @method Cosechas setCosechaId()  Sets the current record's "cosecha_id" value
 * @method Cosechas setDescos()     Sets the current record's "descos" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCosechas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cosechas');
        $this->hasColumn('cosecha_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descos', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}