<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tiporeclamo', 'doctrine');

/**
 * BaseTiporeclamo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo
 * @property string $descri
 * 
 * @method integer     getIdTipo()  Returns the current record's "id_tipo" value
 * @method string      getDescri()  Returns the current record's "descri" value
 * @method Tiporeclamo setIdTipo()  Sets the current record's "id_tipo" value
 * @method Tiporeclamo setDescri()  Sets the current record's "descri" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiporeclamo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tiporeclamo');
        $this->hasColumn('id_tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descri', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}