<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Novedades', 'doctrine');

/**
 * BaseNovedades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $col2
 * 
 * @method integer   getId()   Returns the current record's "id" value
 * @method integer   getCol2() Returns the current record's "col2" value
 * @method Novedades setId()   Sets the current record's "id" value
 * @method Novedades setCol2() Sets the current record's "col2" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNovedades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('novedades');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('col2', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}