<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Linestk', 'doctrine');

/**
 * BaseLinestk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codlin
 * @property string $deslin
 * @property Doctrine_Collection $Catalogo
 * 
 * @method integer             getCodlin()   Returns the current record's "codlin" value
 * @method string              getDeslin()   Returns the current record's "deslin" value
 * @method Doctrine_Collection getCatalogo() Returns the current record's "Catalogo" collection
 * @method Linestk             setCodlin()   Sets the current record's "codlin" value
 * @method Linestk             setDeslin()   Sets the current record's "deslin" value
 * @method Linestk             setCatalogo() Sets the current record's "Catalogo" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLinestk extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linestk');
        $this->hasColumn('codlin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('deslin', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Catalogo', array(
             'local' => 'codlin',
             'foreign' => 'codlin'));
    }
}