<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rhistrem', 'doctrine');

/**
 * BaseRhistrem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nroped
 * @property integer $nroren
 * @property integer $codent
 * @property date $fecha
 * @property float $codart
 * @property integer $valatr1
 * @property integer $valatr2
 * @property integer $valatr3
 * @property integer $valatr4
 * @property float $cantidad
 * @property float $precio
 * @property float $porcbon
 * @property float $impsub
 * @property float $canpes
 * @property integer $codage
 * @property integer $canxenv
 * @property integer $cantpal
 * @property decimal $pbonif1
 * @property decimal $pbonif2
 * @property decimal $precbon
 * @property integer $codemp
 * @property integer $codcom
 * @property integer $codtal
 * @property integer $numero
 * @property date $fecent
 * @property integer $lugent
 * @property integer $coddes
 * @property integer $codfam
 * @property integer $codsfa
 * @property float $cantcan
 * @property float $cantapl
 * 
 * @method integer  getNroped()   Returns the current record's "nroped" value
 * @method integer  getNroren()   Returns the current record's "nroren" value
 * @method integer  getCodent()   Returns the current record's "codent" value
 * @method date     getFecha()    Returns the current record's "fecha" value
 * @method float    getCodart()   Returns the current record's "codart" value
 * @method integer  getValatr1()  Returns the current record's "valatr1" value
 * @method integer  getValatr2()  Returns the current record's "valatr2" value
 * @method integer  getValatr3()  Returns the current record's "valatr3" value
 * @method integer  getValatr4()  Returns the current record's "valatr4" value
 * @method float    getCantidad() Returns the current record's "cantidad" value
 * @method float    getPrecio()   Returns the current record's "precio" value
 * @method float    getPorcbon()  Returns the current record's "porcbon" value
 * @method float    getImpsub()   Returns the current record's "impsub" value
 * @method float    getCanpes()   Returns the current record's "canpes" value
 * @method integer  getCodage()   Returns the current record's "codage" value
 * @method integer  getCanxenv()  Returns the current record's "canxenv" value
 * @method integer  getCantpal()  Returns the current record's "cantpal" value
 * @method decimal  getPbonif1()  Returns the current record's "pbonif1" value
 * @method decimal  getPbonif2()  Returns the current record's "pbonif2" value
 * @method decimal  getPrecbon()  Returns the current record's "precbon" value
 * @method integer  getCodemp()   Returns the current record's "codemp" value
 * @method integer  getCodcom()   Returns the current record's "codcom" value
 * @method integer  getCodtal()   Returns the current record's "codtal" value
 * @method integer  getNumero()   Returns the current record's "numero" value
 * @method date     getFecent()   Returns the current record's "fecent" value
 * @method integer  getLugent()   Returns the current record's "lugent" value
 * @method integer  getCoddes()   Returns the current record's "coddes" value
 * @method integer  getCodfam()   Returns the current record's "codfam" value
 * @method integer  getCodsfa()   Returns the current record's "codsfa" value
 * @method float    getCantcan()  Returns the current record's "cantcan" value
 * @method float    getCantapl()  Returns the current record's "cantapl" value
 * @method Rhistrem setNroped()   Sets the current record's "nroped" value
 * @method Rhistrem setNroren()   Sets the current record's "nroren" value
 * @method Rhistrem setCodent()   Sets the current record's "codent" value
 * @method Rhistrem setFecha()    Sets the current record's "fecha" value
 * @method Rhistrem setCodart()   Sets the current record's "codart" value
 * @method Rhistrem setValatr1()  Sets the current record's "valatr1" value
 * @method Rhistrem setValatr2()  Sets the current record's "valatr2" value
 * @method Rhistrem setValatr3()  Sets the current record's "valatr3" value
 * @method Rhistrem setValatr4()  Sets the current record's "valatr4" value
 * @method Rhistrem setCantidad() Sets the current record's "cantidad" value
 * @method Rhistrem setPrecio()   Sets the current record's "precio" value
 * @method Rhistrem setPorcbon()  Sets the current record's "porcbon" value
 * @method Rhistrem setImpsub()   Sets the current record's "impsub" value
 * @method Rhistrem setCanpes()   Sets the current record's "canpes" value
 * @method Rhistrem setCodage()   Sets the current record's "codage" value
 * @method Rhistrem setCanxenv()  Sets the current record's "canxenv" value
 * @method Rhistrem setCantpal()  Sets the current record's "cantpal" value
 * @method Rhistrem setPbonif1()  Sets the current record's "pbonif1" value
 * @method Rhistrem setPbonif2()  Sets the current record's "pbonif2" value
 * @method Rhistrem setPrecbon()  Sets the current record's "precbon" value
 * @method Rhistrem setCodemp()   Sets the current record's "codemp" value
 * @method Rhistrem setCodcom()   Sets the current record's "codcom" value
 * @method Rhistrem setCodtal()   Sets the current record's "codtal" value
 * @method Rhistrem setNumero()   Sets the current record's "numero" value
 * @method Rhistrem setFecent()   Sets the current record's "fecent" value
 * @method Rhistrem setLugent()   Sets the current record's "lugent" value
 * @method Rhistrem setCoddes()   Sets the current record's "coddes" value
 * @method Rhistrem setCodfam()   Sets the current record's "codfam" value
 * @method Rhistrem setCodsfa()   Sets the current record's "codsfa" value
 * @method Rhistrem setCantcan()  Sets the current record's "cantcan" value
 * @method Rhistrem setCantapl()  Sets the current record's "cantapl" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRhistrem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rhistrem');
        $this->hasColumn('nroped', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nroren', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('codart', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('valatr1', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('valatr2', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('valatr3', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('valatr4', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cantidad', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('precio', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('porcbon', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('impsub', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('canpes', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('codage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('canxenv', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cantpal', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('pbonif1', 'decimal', 15, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             'scale' => '2',
             ));
        $this->hasColumn('pbonif2', 'decimal', 15, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             'scale' => '2',
             ));
        $this->hasColumn('precbon', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '2',
             ));
        $this->hasColumn('codemp', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codcom', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codtal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecent', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('lugent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('coddes', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codfam', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codsfa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cantcan', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('cantapl', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}