<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Novcoinf', 'doctrine');

/**
 * BaseNovcoinf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo
 * @property integer $leecli
 * @property integer $leepro
 * @property date $dfecha
 * @property date $hfecha
 * @property integer $estado
 * @property string $titulo
 * @property string $resumen
 * @property string $detalle
 * @property string $imagen
 * @property string $archivo
 * @property string $nbreimg
 * @property string $nbrearch
 * 
 * @method integer  getId()       Returns the current record's "id" value
 * @method integer  getTipo()     Returns the current record's "tipo" value
 * @method integer  getLeecli()   Returns the current record's "leecli" value
 * @method integer  getLeepro()   Returns the current record's "leepro" value
 * @method date     getDfecha()   Returns the current record's "dfecha" value
 * @method date     getHfecha()   Returns the current record's "hfecha" value
 * @method integer  getEstado()   Returns the current record's "estado" value
 * @method string   getTitulo()   Returns the current record's "titulo" value
 * @method string   getResumen()  Returns the current record's "resumen" value
 * @method string   getDetalle()  Returns the current record's "detalle" value
 * @method string   getImagen()   Returns the current record's "imagen" value
 * @method string   getArchivo()  Returns the current record's "archivo" value
 * @method string   getNbreimg()  Returns the current record's "nbreimg" value
 * @method string   getNbrearch() Returns the current record's "nbrearch" value
 * @method Novcoinf setId()       Sets the current record's "id" value
 * @method Novcoinf setTipo()     Sets the current record's "tipo" value
 * @method Novcoinf setLeecli()   Sets the current record's "leecli" value
 * @method Novcoinf setLeepro()   Sets the current record's "leepro" value
 * @method Novcoinf setDfecha()   Sets the current record's "dfecha" value
 * @method Novcoinf setHfecha()   Sets the current record's "hfecha" value
 * @method Novcoinf setEstado()   Sets the current record's "estado" value
 * @method Novcoinf setTitulo()   Sets the current record's "titulo" value
 * @method Novcoinf setResumen()  Sets the current record's "resumen" value
 * @method Novcoinf setDetalle()  Sets the current record's "detalle" value
 * @method Novcoinf setImagen()   Sets the current record's "imagen" value
 * @method Novcoinf setArchivo()  Sets the current record's "archivo" value
 * @method Novcoinf setNbreimg()  Sets the current record's "nbreimg" value
 * @method Novcoinf setNbrearch() Sets the current record's "nbrearch" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNovcoinf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('novcoinf');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('leecli', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('leepro', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('dfecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hfecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('titulo', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('resumen', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('detalle', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 300,
             ));
        $this->hasColumn('imagen', 'string', 55, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 55,
             ));
        $this->hasColumn('archivo', 'string', 55, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 55,
             ));
        $this->hasColumn('nbreimg', 'string', 55, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 55,
             ));
        $this->hasColumn('nbrearch', 'string', 55, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 55,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}