<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tpagoxent', 'doctrine');

/**
 * BaseTpagoxent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $codpag
 * @property decimal $codent
 * @property integer $codage
 * 
 * @method decimal   getCodpag() Returns the current record's "codpag" value
 * @method decimal   getCodent() Returns the current record's "codent" value
 * @method integer   getCodage() Returns the current record's "codage" value
 * @method Tpagoxent setCodpag() Sets the current record's "codpag" value
 * @method Tpagoxent setCodent() Sets the current record's "codent" value
 * @method Tpagoxent setCodage() Sets the current record's "codage" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTpagoxent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tpagoxent');
        $this->hasColumn('codpag', 'decimal', 4, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codent', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('codage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}