<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cconpago', 'doctrine');

/**
 * BaseCconpago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codcpag
 * @property string $descpag
 * 
 * @method integer  getCodcpag() Returns the current record's "codcpag" value
 * @method string   getDescpag() Returns the current record's "descpag" value
 * @method Cconpago setCodcpag() Sets the current record's "codcpag" value
 * @method Cconpago setDescpag() Sets the current record's "descpag" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCconpago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cconpago');
        $this->hasColumn('codcpag', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descpag', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}