<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserReclamos', 'doctrine');

/**
 * BaseUserReclamos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $webuser
 * @property string $webpwd
 * 
 * @method integer      getId()      Returns the current record's "id" value
 * @method string       getWebuser() Returns the current record's "webuser" value
 * @method string       getWebpwd()  Returns the current record's "webpwd" value
 * @method UserReclamos setId()      Sets the current record's "id" value
 * @method UserReclamos setWebuser() Sets the current record's "webuser" value
 * @method UserReclamos setWebpwd()  Sets the current record's "webpwd" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserReclamos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_reclamos');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('webuser', 'string', 64, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('webpwd', 'string', 64, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}