<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cereales', 'doctrine');

/**
 * BaseCereales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cereal_id
 * @property string $descer
 * 
 * @method integer  getCerealId()  Returns the current record's "cereal_id" value
 * @method string   getDescer()    Returns the current record's "descer" value
 * @method Cereales setCerealId()  Sets the current record's "cereal_id" value
 * @method Cereales setDescer()    Sets the current record's "descer" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCereales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cereales');
        $this->hasColumn('cereal_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descer', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}