<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estadorecl', 'doctrine');

/**
 * BaseEstadorecl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_reclamo
 * @property integer $id_estado
 * @property integer $id_tiporecl
 * @property string $respuesta
 * @property date $fecha
 * @property time $hora
 * @property integer $usuario
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method integer    getIdReclamo()   Returns the current record's "id_reclamo" value
 * @method integer    getIdEstado()    Returns the current record's "id_estado" value
 * @method integer    getIdTiporecl()  Returns the current record's "id_tiporecl" value
 * @method string     getRespuesta()   Returns the current record's "respuesta" value
 * @method date       getFecha()       Returns the current record's "fecha" value
 * @method time       getHora()        Returns the current record's "hora" value
 * @method integer    getUsuario()     Returns the current record's "usuario" value
 * @method Estadorecl setId()          Sets the current record's "id" value
 * @method Estadorecl setIdReclamo()   Sets the current record's "id_reclamo" value
 * @method Estadorecl setIdEstado()    Sets the current record's "id_estado" value
 * @method Estadorecl setIdTiporecl()  Sets the current record's "id_tiporecl" value
 * @method Estadorecl setRespuesta()   Sets the current record's "respuesta" value
 * @method Estadorecl setFecha()       Sets the current record's "fecha" value
 * @method Estadorecl setHora()        Sets the current record's "hora" value
 * @method Estadorecl setUsuario()     Sets the current record's "usuario" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadorecl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estadorecl');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_reclamo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tiporecl', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('respuesta', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}