<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Entxuser', 'doctrine');

/**
 * BaseEntxuser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuarios_id
 * @property integer $entidad_id
 * @property integer $id
 * 
 * @method integer  getUsuariosId()  Returns the current record's "usuarios_id" value
 * @method integer  getEntidadId()   Returns the current record's "entidad_id" value
 * @method integer  getId()          Returns the current record's "id" value
 * @method Entxuser setUsuariosId()  Sets the current record's "usuarios_id" value
 * @method Entxuser setEntidadId()   Sets the current record's "entidad_id" value
 * @method Entxuser setId()          Sets the current record's "id" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntxuser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entxuser');
        $this->hasColumn('usuarios_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('entidad_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}