<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Lugent', 'doctrine');

/**
 * BaseLugent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $codigo
 * @property integer $codlug
 * @property string $descri
 * @property string $longitud
 * @property string $latitud
 * @property string $observacion
 * 
 * @method decimal getCodigo()      Returns the current record's "codigo" value
 * @method integer getCodlug()      Returns the current record's "codlug" value
 * @method string  getDescri()      Returns the current record's "descri" value
 * @method string  getLongitud()    Returns the current record's "longitud" value
 * @method string  getLatitud()     Returns the current record's "latitud" value
 * @method string  getObservacion() Returns the current record's "observacion" value
 * @method Lugent  setCodigo()      Sets the current record's "codigo" value
 * @method Lugent  setCodlug()      Sets the current record's "codlug" value
 * @method Lugent  setDescri()      Sets the current record's "descri" value
 * @method Lugent  setLongitud()    Sets the current record's "longitud" value
 * @method Lugent  setLatitud()     Sets the current record's "latitud" value
 * @method Lugent  setObservacion() Sets the current record's "observacion" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLugent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lugent');
        $this->hasColumn('codigo', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('codlug', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descri', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 300,
             ));
        $this->hasColumn('longitud', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('latitud', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('observacion', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 300,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}