<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Loguser', 'doctrine');

/**
 * BaseLoguser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $usuario
 * @property date $fecha
 * @property time $hora
 * @property string $ip
 * @property string $accion
 * @property integer $usuario_id
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getUsuario()    Returns the current record's "usuario" value
 * @method date    getFecha()      Returns the current record's "fecha" value
 * @method time    getHora()       Returns the current record's "hora" value
 * @method string  getIp()         Returns the current record's "ip" value
 * @method string  getAccion()     Returns the current record's "accion" value
 * @method integer getUsuarioId()  Returns the current record's "usuario_id" value
 * @method Loguser setId()         Sets the current record's "id" value
 * @method Loguser setUsuario()    Sets the current record's "usuario" value
 * @method Loguser setFecha()      Sets the current record's "fecha" value
 * @method Loguser setHora()       Sets the current record's "hora" value
 * @method Loguser setIp()         Sets the current record's "ip" value
 * @method Loguser setAccion()     Sets the current record's "accion" value
 * @method Loguser setUsuarioId()  Sets the current record's "usuario_id" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLoguser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('loguser');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('usuario', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('ip', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('accion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('usuario_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}