<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mailxent', 'doctrine');

/**
 * BaseMailxent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codent
 * @property integer $nroren
 * @property string $nombre
 * @property string $email
 * @property string $nrocel
 * 
 * @method integer  getCodent() Returns the current record's "codent" value
 * @method integer  getNroren() Returns the current record's "nroren" value
 * @method string   getNombre() Returns the current record's "nombre" value
 * @method string   getEmail()  Returns the current record's "email" value
 * @method string   getNrocel() Returns the current record's "nrocel" value
 * @method Mailxent setCodent() Sets the current record's "codent" value
 * @method Mailxent setNroren() Sets the current record's "nroren" value
 * @method Mailxent setNombre() Sets the current record's "nombre" value
 * @method Mailxent setEmail()  Sets the current record's "email" value
 * @method Mailxent setNrocel() Sets the current record's "nrocel" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailxent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailxent');
        $this->hasColumn('codent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nroren', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('email', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 60,
             ));
        $this->hasColumn('nrocel', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}