<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Fichadet', 'doctrine');

/**
 * BaseFichadet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $codemp
 * @property integer $codcom
 * @property integer $codtal
 * @property integer $numero
 * @property integer $codigo
 * @property integer $codres
 * @property date $fecha
 * @property string $descom
 * @property string $numpre
 * @property integer $cosecha
 * @property integer $cereal
 * @property float $kilos1
 * @property float $kilos2
 * @property float $kilos3
 * @property float $kilos4
 * @property float $kilos5
 * @property float $kilos6
 * @property float $kilos7
 * @property float $kilstk
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method integer  getCodemp()  Returns the current record's "codemp" value
 * @method integer  getCodcom()  Returns the current record's "codcom" value
 * @method integer  getCodtal()  Returns the current record's "codtal" value
 * @method integer  getNumero()  Returns the current record's "numero" value
 * @method integer  getCodigo()  Returns the current record's "codigo" value
 * @method integer  getCodres()  Returns the current record's "codres" value
 * @method date     getFecha()   Returns the current record's "fecha" value
 * @method string   getDescom()  Returns the current record's "descom" value
 * @method string   getNumpre()  Returns the current record's "numpre" value
 * @method integer  getCosecha() Returns the current record's "cosecha" value
 * @method integer  getCereal()  Returns the current record's "cereal" value
 * @method float    getKilos1()  Returns the current record's "kilos1" value
 * @method float    getKilos2()  Returns the current record's "kilos2" value
 * @method float    getKilos3()  Returns the current record's "kilos3" value
 * @method float    getKilos4()  Returns the current record's "kilos4" value
 * @method float    getKilos5()  Returns the current record's "kilos5" value
 * @method float    getKilos6()  Returns the current record's "kilos6" value
 * @method float    getKilos7()  Returns the current record's "kilos7" value
 * @method float    getKilstk()  Returns the current record's "kilstk" value
 * @method Fichadet setId()      Sets the current record's "id" value
 * @method Fichadet setCodemp()  Sets the current record's "codemp" value
 * @method Fichadet setCodcom()  Sets the current record's "codcom" value
 * @method Fichadet setCodtal()  Sets the current record's "codtal" value
 * @method Fichadet setNumero()  Sets the current record's "numero" value
 * @method Fichadet setCodigo()  Sets the current record's "codigo" value
 * @method Fichadet setCodres()  Sets the current record's "codres" value
 * @method Fichadet setFecha()   Sets the current record's "fecha" value
 * @method Fichadet setDescom()  Sets the current record's "descom" value
 * @method Fichadet setNumpre()  Sets the current record's "numpre" value
 * @method Fichadet setCosecha() Sets the current record's "cosecha" value
 * @method Fichadet setCereal()  Sets the current record's "cereal" value
 * @method Fichadet setKilos1()  Sets the current record's "kilos1" value
 * @method Fichadet setKilos2()  Sets the current record's "kilos2" value
 * @method Fichadet setKilos3()  Sets the current record's "kilos3" value
 * @method Fichadet setKilos4()  Sets the current record's "kilos4" value
 * @method Fichadet setKilos5()  Sets the current record's "kilos5" value
 * @method Fichadet setKilos6()  Sets the current record's "kilos6" value
 * @method Fichadet setKilos7()  Sets the current record's "kilos7" value
 * @method Fichadet setKilstk()  Sets the current record's "kilstk" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFichadet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fichadet');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codemp', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('codcom', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codtal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codres', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('descom', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('numpre', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('cosecha', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cereal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kilos1', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('kilos2', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('kilos3', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('kilos4', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('kilos5', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('kilos6', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('kilos7', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('kilstk', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}