<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mdatenti', 'doctrine');

/**
 * BaseMdatenti
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_id
 * @property integer $codvend
 * @property integer $codzona
 * 
 * @method integer  getCodigoId()  Returns the current record's "codigo_id" value
 * @method integer  getCodvend()   Returns the current record's "codvend" value
 * @method integer  getCodzona()   Returns the current record's "codzona" value
 * @method Mdatenti setCodigoId()  Sets the current record's "codigo_id" value
 * @method Mdatenti setCodvend()   Sets the current record's "codvend" value
 * @method Mdatenti setCodzona()   Sets the current record's "codzona" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMdatenti extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mdatenti');
        $this->hasColumn('codigo_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codvend', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codzona', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}