<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Marcstk', 'doctrine');

/**
 * BaseMarcstk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codmar
 * @property string $desmar
 * @property Doctrine_Collection $Catalogo
 * 
 * @method integer             getCodmar()   Returns the current record's "codmar" value
 * @method string              getDesmar()   Returns the current record's "desmar" value
 * @method Doctrine_Collection getCatalogo() Returns the current record's "Catalogo" collection
 * @method Marcstk             setCodmar()   Sets the current record's "codmar" value
 * @method Marcstk             setDesmar()   Sets the current record's "desmar" value
 * @method Marcstk             setCatalogo() Sets the current record's "Catalogo" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMarcstk extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('marcstk');
        $this->hasColumn('codmar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('desmar', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Catalogo', array(
             'local' => 'codmar',
             'foreign' => 'codmar'));
    }
}