<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Entresum', 'doctrine');

/**
 * BaseEntresum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo
 * @property integer $codres
 * @property string $razsoc
 * 
 * @method integer  getCodigo() Returns the current record's "codigo" value
 * @method integer  getCodres() Returns the current record's "codres" value
 * @method string   getRazsoc() Returns the current record's "razsoc" value
 * @method Entresum setCodigo() Sets the current record's "codigo" value
 * @method Entresum setCodres() Sets the current record's "codres" value
 * @method Entresum setRazsoc() Sets the current record's "razsoc" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntresum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entresum');
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codres', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('razsoc', 'string', 100, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}