<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vendedor', 'doctrine');

/**
 * BaseVendedor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo
 * @property string $descripcion
 * @property string $mail
 * @property string $telefono
 * 
 * @method integer  getCodigo()      Returns the current record's "codigo" value
 * @method string   getDescripcion() Returns the current record's "descripcion" value
 * @method string   getMail()        Returns the current record's "mail" value
 * @method string   getTelefono()    Returns the current record's "telefono" value
 * @method Vendedor setCodigo()      Sets the current record's "codigo" value
 * @method Vendedor setDescripcion() Sets the current record's "descripcion" value
 * @method Vendedor setMail()        Sets the current record's "mail" value
 * @method Vendedor setTelefono()    Sets the current record's "telefono" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVendedor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vendedor');
        $this->hasColumn('codigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descripcion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('mail', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('telefono', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}