<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tipounid', 'doctrine');

/**
 * BaseTipounid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $coduni
 * @property string $desuni
 * @property Doctrine_Collection $Catalogo
 * 
 * @method integer             getCoduni()   Returns the current record's "coduni" value
 * @method string              getDesuni()   Returns the current record's "desuni" value
 * @method Doctrine_Collection getCatalogo() Returns the current record's "Catalogo" collection
 * @method Tipounid            setCoduni()   Sets the current record's "coduni" value
 * @method Tipounid            setDesuni()   Sets the current record's "desuni" value
 * @method Tipounid            setCatalogo() Sets the current record's "Catalogo" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipounid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipounid');
        $this->hasColumn('coduni', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('desuni', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Catalogo', array(
             'local' => 'coduni',
             'foreign' => 'unistk'));
    }
}