<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Uninego', 'doctrine');

/**
 * BaseUninego
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $codage
 * @property string $descri
 * 
 * @method decimal getCodage() Returns the current record's "codage" value
 * @method string  getDescri() Returns the current record's "descri" value
 * @method Uninego setCodage() Sets the current record's "codage" value
 * @method Uninego setDescri() Sets the current record's "descri" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUninego extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uninego');
        $this->hasColumn('codage', 'decimal', 2, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('descri', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}