<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cpedxweb', 'doctrine');

/**
 * BaseCpedxweb
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $nroped
 * @property integer $codent
 * @property date $fecha
 * @property time $hora
 * @property float $impsub
 * @property float $imptot
 * @property integer $estado
 * @property integer $retcli
 * @property integer $lugent
 * @property integer $tipoped
 * @property integer $tipopago
 * @property integer $coddes
 * @property string $observ
 * @property integer $codage
 * @property integer $favorito
 * @property integer $codemp
 * @property integer $codcom
 * @property integer $codtal
 * @property integer $numero
 * @property float $impdes
 * @property float $pordes
 * @property float $imppib
 * @property float $porpib
 * @property float $impiva
 * @property integer $totpes
 * @property integer $codcpag
 * @property string $docref
 * @property Doctrine_Collection $Rpedxweb
 * 
 * @method integer             getNroped()   Returns the current record's "nroped" value
 * @method integer             getCodent()   Returns the current record's "codent" value
 * @method date                getFecha()    Returns the current record's "fecha" value
 * @method time                getHora()     Returns the current record's "hora" value
 * @method float               getImpsub()   Returns the current record's "impsub" value
 * @method float               getImptot()   Returns the current record's "imptot" value
 * @method integer             getEstado()   Returns the current record's "estado" value
 * @method integer             getRetcli()   Returns the current record's "retcli" value
 * @method integer             getLugent()   Returns the current record's "lugent" value
 * @method integer             getTipoped()  Returns the current record's "tipoped" value
 * @method integer             getTipopago() Returns the current record's "tipopago" value
 * @method integer             getCoddes()   Returns the current record's "coddes" value
 * @method string              getObserv()   Returns the current record's "observ" value
 * @method integer             getCodage()   Returns the current record's "codage" value
 * @method integer             getFavorito() Returns the current record's "favorito" value
 * @method integer             getCodemp()   Returns the current record's "codemp" value
 * @method integer             getCodcom()   Returns the current record's "codcom" value
 * @method integer             getCodtal()   Returns the current record's "codtal" value
 * @method integer             getNumero()   Returns the current record's "numero" value
 * @method float               getImpdes()   Returns the current record's "impdes" value
 * @method float               getPordes()   Returns the current record's "pordes" value
 * @method float               getImppib()   Returns the current record's "imppib" value
 * @method float               getPorpib()   Returns the current record's "porpib" value
 * @method float               getImpiva()   Returns the current record's "impiva" value
 * @method integer             getTotpes()   Returns the current record's "totpes" value
 * @method integer             getCodcpag()  Returns the current record's "codcpag" value
 * @method string              getDocref()   Returns the current record's "docref" value
 * @method Doctrine_Collection getRpedxweb() Returns the current record's "Rpedxweb" collection
 * @method Cpedxweb            setNroped()   Sets the current record's "nroped" value
 * @method Cpedxweb            setCodent()   Sets the current record's "codent" value
 * @method Cpedxweb            setFecha()    Sets the current record's "fecha" value
 * @method Cpedxweb            setHora()     Sets the current record's "hora" value
 * @method Cpedxweb            setImpsub()   Sets the current record's "impsub" value
 * @method Cpedxweb            setImptot()   Sets the current record's "imptot" value
 * @method Cpedxweb            setEstado()   Sets the current record's "estado" value
 * @method Cpedxweb            setRetcli()   Sets the current record's "retcli" value
 * @method Cpedxweb            setLugent()   Sets the current record's "lugent" value
 * @method Cpedxweb            setTipoped()  Sets the current record's "tipoped" value
 * @method Cpedxweb            setTipopago() Sets the current record's "tipopago" value
 * @method Cpedxweb            setCoddes()   Sets the current record's "coddes" value
 * @method Cpedxweb            setObserv()   Sets the current record's "observ" value
 * @method Cpedxweb            setCodage()   Sets the current record's "codage" value
 * @method Cpedxweb            setFavorito() Sets the current record's "favorito" value
 * @method Cpedxweb            setCodemp()   Sets the current record's "codemp" value
 * @method Cpedxweb            setCodcom()   Sets the current record's "codcom" value
 * @method Cpedxweb            setCodtal()   Sets the current record's "codtal" value
 * @method Cpedxweb            setNumero()   Sets the current record's "numero" value
 * @method Cpedxweb            setImpdes()   Sets the current record's "impdes" value
 * @method Cpedxweb            setPordes()   Sets the current record's "pordes" value
 * @method Cpedxweb            setImppib()   Sets the current record's "imppib" value
 * @method Cpedxweb            setPorpib()   Sets the current record's "porpib" value
 * @method Cpedxweb            setImpiva()   Sets the current record's "impiva" value
 * @method Cpedxweb            setTotpes()   Sets the current record's "totpes" value
 * @method Cpedxweb            setCodcpag()  Sets the current record's "codcpag" value
 * @method Cpedxweb            setDocref()   Sets the current record's "docref" value
 * @method Cpedxweb            setRpedxweb() Sets the current record's "Rpedxweb" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCpedxweb extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cpedxweb');
        $this->hasColumn('nroped', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('impsub', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('imptot', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('estado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('retcli', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('lugent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tipoped', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tipopago', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('coddes', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('observ', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '.',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 300,
             ));
        $this->hasColumn('codage', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('favorito', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('codemp', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codcom', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codtal', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('numero', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('impdes', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('pordes', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('imppib', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('porpib', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('impiva', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('totpes', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codcpag', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('docref', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rpedxweb', array(
             'local' => 'nroped',
             'foreign' => 'nroped'));
    }
}