<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subfstk', 'doctrine');

/**
 * BaseSubfstk
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codfam
 * @property integer $codsfa
 * @property string $descri
 * @property Doctrine_Collection $Catalogo
 * @property Doctrine_Collection $Catalogo_3
 * 
 * @method integer             getCodfam()     Returns the current record's "codfam" value
 * @method integer             getCodsfa()     Returns the current record's "codsfa" value
 * @method string              getDescri()     Returns the current record's "descri" value
 * @method Doctrine_Collection getCatalogo()   Returns the current record's "Catalogo" collection
 * @method Doctrine_Collection getCatalogo3()  Returns the current record's "Catalogo_3" collection
 * @method Subfstk             setCodfam()     Sets the current record's "codfam" value
 * @method Subfstk             setCodsfa()     Sets the current record's "codsfa" value
 * @method Subfstk             setDescri()     Sets the current record's "descri" value
 * @method Subfstk             setCatalogo()   Sets the current record's "Catalogo" collection
 * @method Subfstk             setCatalogo3()  Sets the current record's "Catalogo_3" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubfstk extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subfstk');
        $this->hasColumn('codfam', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('codsfa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descri', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Catalogo', array(
             'local' => 'codfam',
             'foreign' => 'codfam'));

        $this->hasMany('Catalogo as Catalogo_3', array(
             'local' => 'codsfa',
             'foreign' => 'codsfa'));
    }
}