<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/01/16 17:34:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ew2',
  'username' => 'root',
  'password' => 'rosam0nt3',
  'name' => 'doctrine',
)),);
