<?php

/**
 * CconpagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CconpagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CconpagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cconpago');
    }
}