<?php

/**
 * CerealesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CerealesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CerealesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cereales');
    }
}