<?php

/**
 * ChistremTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChistremTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChistremTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chistrem');
    }
}