<?php

/**
 * ChistpedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChistpedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChistpedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chistped');
    }
}