<?php

/**
 * CosechasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CosechasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CosechasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cosechas');
    }
}