<?php

/**
 * CpedxwebTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpedxwebTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpedxwebTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cpedxweb');
    }
}