<?php

/**
 * CpedfavTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CpedfavTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CpedfavTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cpedfav');
    }
}