<?php

/**
 * CreclamoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CreclamoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CreclamoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Creclamo');
    }
}