<?php

/**
 * DefectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DefectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DefectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Defecto');
    }
}