<?php

/**
 * EntidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Entidad');
    }
}