<?php

/**
 * EntresumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntresumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntresumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Entresum');
    }
}