<?php

/**
 * Entxuser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Entxuser extends BaseEntxuser
{
	public function getEnti()
	{
		$entxusr = Doctrine_Core::getTable('entxuser')
		->createQuery('co')
		->where('usuarios_id = ?', $this->getUsuariosId())
		->fetchOne();
	
		if (!empty($entxusr)){
			$entidad = Doctrine_Core::getTable('entidad')
			->createQuery('co')
			->where('codigo_id = ?', $entxusr->getEntidad_id())
			->fetchOne();
	
			if (!empty($entidad)){
				return $entidad->getRazsoc();
			}else{
				return ' - ';
			}
		}else {return ' - ';
		}
	}
}
