<?php

/**
 * EntxuserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntxuserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntxuserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Entxuser');
    }
}