<?php

/**
 * EstadoreclTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoreclTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoreclTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estadorecl');
    }
}