<?php

/**
 * FamistkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FamistkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FamistkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Famistk');
    }
}