<?php

/**
 * Fichares
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fichares extends BaseFichares
{

	public function getCereal_descer()
	{
		$cereal = Doctrine_Core::getTable('cereales')
		->createQuery('c')
		->where('cereal_id = ?', $this->getCereal())
		->fetchOne();
	
		if (!empty($cereal)){
			return $cereal->getdescer();
		}else{
			return ' - ';
		}
	}
	
	public function getCosecha_descos()
	{
		$cosecha = Doctrine_Core::getTable('cosechas')
		->createQuery('co')
		->where('cosecha_id = ?', $this->getCosecha())
		->fetchOne();
	
		if (!empty($cosecha)){
			return $cosecha->getdescos();
		}else{
			return ' - ';
		}
	}
}
