<?php

/**
 * FicharesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FicharesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FicharesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fichares');
    }
}