<?php

/**
 * LinestkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinestkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinestkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Linestk');
    }
}