<?php

/**
 * LugdxentiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LugdxentiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LugdxentiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lugdxenti');
    }
}