<?php

/**
 * LugdesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LugdesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LugdesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lugdes');
    }
}