<?php

/**
 * LugentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LugentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LugentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lugent');
    }
}