<?php

/**
 * MailxentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailxentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailxentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mailxent');
    }
}