<?php

/**
 * MarcstkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MarcstkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MarcstkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Marcstk');
    }
}