<?php

/**
 * NovcoinfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NovcoinfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NovcoinfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Novcoinf');
    }
}