<?php

/**
 * ProxentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProxentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProxentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proxent');
    }
}