<?php

/**
 * RencbtefTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RencbtefTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RencbtefTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rencbtef');
    }
}