<?php

/**
 * RencbtecTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RencbtecTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RencbtecTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rencbtec');
    }
}