<?php

/**
 * RhistremTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RhistremTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RhistremTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rhistrem');
    }
}