<?php

/**
 * RhistpedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RhistpedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RhistpedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rhistped');
    }
}