<?php

/**
 * RpedfavTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RpedfavTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RpedfavTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rpedfav');
    }
}