<?php

/**
 * RubrstkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RubrstkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RubrstkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rubrstk');
    }
}