<?php

/**
 * SubfstkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubfstkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubfstkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subfstk');
    }
}