<?php

/**
 * TipounidTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipounidTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipounidTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipounid');
    }
}