<?php

/**
 * TiporeclamoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiporeclamoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiporeclamoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tiporeclamo');
    }
}