<?php

/**
 * TipopediTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipopediTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipopediTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipopedi');
    }
}