<?php

/**
 * TpagoxentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TpagoxentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TpagoxentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tpagoxent');
    }
}