<?php

/**
 * TpedxentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TpedxentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TpedxentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tpedxent');
    }
}