<?php

/**
 * UninegoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UninegoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UninegoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Uninego');
    }
}