<?php

/**
 * UserReclamosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserReclamosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserReclamosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserReclamos');
    }
}