<?php

/**
 * ZonasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZonasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZonasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zonas');
    }
}